### ISSUE TITLE
Enllaços caiguts

### ISSUE THREAD

**Issue by ghost** [miquelt9/IC-FIB#2]
Holi, els enllaços estan caiguts a partir del tema 6. Es pot arreglar?

**Comment by miquelt9** [comment]
Hola! Moltes gràcies per avisar m'ho miro i ho arreglo :)

**Comment by miquelt9** [comment]
Hola @delgado-art, he afegit els documents de forma manual #3 i he ficat links adicionals x facilitar-ne l´accés. Suposo que l´Enric haurà tret els documents per penjar-ne uns altres de més actualitzats quan pertoqui.
Qualsevol altre cosa avisa'm.

Gràcies de nou :)

**Comment by ghost** [comment]
Ets un grande!
